const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let notes=get('j_notes',[]),sessions=get('j_sessions',[]),workouts=get('j_workouts',[]),playlists=get('j_playlists',[{id:'fav',name:'Favourites',notes:[]}]),active='fav',tag='All',start=null,elapsed=0,intv=null;
const day=()=>new Date().toISOString().slice(0,10),fmt=d=>new Date(d).toLocaleString(undefined,{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}),pad=n=>String(n).padStart(2,'0'),dur=s=>`${Math.floor(s/3600)}h ${pad(Math.floor(s%3600/60))}m`,esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function clock(){let d=new Date();$('#clock').textContent=d.toLocaleTimeString();$('#today').textContent=d.toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long',year:'numeric'});$('#greet').textContent=d.getHours()<12?'GOOD MORNING':d.getHours()<18?'GOOD AFTERNOON':'GOOD EVENING'}setInterval(clock,1000);clock();
function show(id){$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.section===id));$('#pageTitle').textContent={dashboard:'Dashboard',notes:'Notes',playlists:'Playlists',work:'Work Hours',workouts:'Workouts'}[id]||'Dashboard';closeDrawer()}
$$('[data-section]').forEach(x=>x.onclick=()=>show(x.dataset.section));
document.addEventListener('click',e=>{let n=e.target.closest('[data-new]');if(n)open(n.dataset.new==='note'?'noteModal':n.dataset.new==='playlist'?'playlistModal':'workoutModal');let c=e.target.closest('[data-close]');if(c)$('#'+c.dataset.close).classList.remove('open')});
function card(n){return `<article class="note"><div class="nt"><h3>${esc(n.title)}</h3><span class="tag">${esc(n.tag)}</span></div><p>${esc(n.content)}</p><div class="foot"><span>${n.pinned?'📌 ':''}${fmt(n.updated)}</span><span class="actions"><button class="${n.pinned?'pin':''}" onclick="pin('${n.id}')">${n.pinned?'Unpin':'Pin'}</button><button class="${n.favourite?'pin':''}" onclick="fav('${n.id}')">${n.favourite?'♥':'♡'}</button><button onclick="add('${n.id}')">♫</button><button onclick="edit('${n.id}')">Edit</button><button onclick="del('${n.id}')">×</button></span></div></article>`}
function renderNotes(q=''){q=q.toLowerCase();let a=notes.filter(n=>(tag==='All'||n.tag===tag)&&`${n.title} ${n.content} ${n.tag}`.toLowerCase().includes(q)).sort((a,b)=>b.pinned-a.pinned||new Date(b.updated)-new Date(a.updated));$('#notesGrid').innerHTML=a.map(card).join('')||'<div class="note"><h3>No notes found</h3><p>Create your first note.</p></div>';$('#recent').innerHTML=a.slice(0,3).map(card).join('')||'<div class="note"><h3>Your workspace is ready</h3><p>Create your first note.</p></div>';let tags=['All',...new Set(notes.map(n=>n.tag))];$('#chips').innerHTML=tags.map(x=>`<button class="chip ${x===tag?'active':''}" data-tag="${esc(x)}">${esc(x)}</button>`).join('')}
function save(){set('j_notes',notes);set('j_playlists',playlists);set('j_sessions',sessions);set('j_workouts',workouts)}
window.edit=id=>{let n=notes.find(x=>x.id===id);$('#noteTitleText').textContent='Edit Note';$('#nid').value=n.id;$('#ntitle').value=n.title;$('#ntag').value=n.tag;$('#ncontent').value=n.content;open('noteModal')};
window.del=id=>{if(confirm('Delete this note?')){notes=notes.filter(x=>x.id!==id);playlists.forEach(p=>p.notes=(p.notes||[]).filter(x=>x!==id));save();render()}};
window.pin=id=>{let n=notes.find(x=>x.id===id);n.pinned=!n.pinned;n.updated=new Date().toISOString();save();render()};
window.fav=id=>{let n=notes.find(x=>x.id===id),f=playlists.find(x=>x.id==='fav');n.favourite=!n.favourite;f.notes=f.notes||[];n.favourite&&!f.notes.includes(id)?f.notes.push(id):n.favourite||((f.notes=f.notes.filter(x=>x!==id)));save();render()};
window.add=id=>{let names=playlists.map(x=>x.name).join(', '),name=prompt('Playlist name:\\n'+names,'Favourites');if(!name)return;let p=playlists.find(x=>x.name.toLowerCase()===name.toLowerCase());if(!p){if(!confirm('Create '+name+'?'))return;p={id:crypto.randomUUID(),name,notes:[]};playlists.push(p)}p.notes=p.notes||[];if(!p.notes.includes(id))p.notes.push(id);save();render()};
function open(id){$('#'+id).classList.add('open')}function render(){renderNotes($('#noteSearch')?.value||'');renderPlaylists();renderWork();renderWorkout()}
$('#noteForm').onsubmit=e=>{e.preventDefault();let id=$('#nid').value,old=notes.find(x=>x.id===id),n={id:id||crypto.randomUUID(),title:$('#ntitle').value.trim(),tag:$('#ntag').value,content:$('#ncontent').value.trim(),updated:new Date().toISOString(),pinned:old?.pinned||false,favourite:old?.favourite||false};notes=id?notes.map(x=>x.id===id?n:x):[n,...notes];save();e.target.reset();$('#noteModal').classList.remove('open');render()};
$('#noteSearch').oninput=e=>renderNotes(e.target.value);$('#globalSearch').oninput=e=>{show('notes');$('#noteSearch').value=e.target.value;renderNotes(e.target.value)};$('#chips').onclick=e=>{if(e.target.dataset.tag){tag=e.target.dataset.tag;renderNotes($('#noteSearch').value)}};
function renderPlaylists(){let p=playlists.find(x=>x.id===active)||playlists[0];active=p.id;$('#plist').innerHTML=playlists.map(x=>`<button class="playlist-item ${x.id===active?'active':''}" data-p="${x.id}">♫ ${esc(x.name)} <small>${(x.notes||[]).length}</small></button>`).join('');$('#playlistTitle').textContent=p.name;$('#playlistCount').textContent=(p.notes||[]).length+' notes';$('#playlistNotes').innerHTML=notes.filter(n=>(p.notes||[]).includes(n.id)).map(card).join('')||'<div class="note"><h3>Playlist is empty</h3><p>Use ♫ on a note to add it.</p></div>'}
$('#plist').onclick=e=>{let b=e.target.closest('[data-p]');if(b){active=b.dataset.p;renderPlaylists()}};
$('#playlistForm').onsubmit=e=>{e.preventDefault();let name=$('#pname').value.trim();if(playlists.some(p=>p.name.toLowerCase()===name.toLowerCase()))return alert('Playlist already exists.');playlists.push({id:crypto.randomUUID(),name,notes:[]});active=playlists.at(-1).id;save();e.target.reset();$('#playlistModal').classList.remove('open');renderPlaylists()};
function renderWork(){let total=sessions.filter(s=>s.date===day()).reduce((a,s)=>a+s.seconds,0);$('#dashWork').textContent=dur(total);$('#workTotal').textContent=dur(total);$('#sessions').innerHTML=sessions.filter(s=>s.date===day()).slice().reverse().map(s=>`<div class="row"><div><b>Work session</b><p>${fmt(s.created)}</p></div><b>${dur(s.seconds)}</b></div>`).join('')||'<p style="color:var(--m)">No work sessions today.</p>'}
function tick(){elapsed=Math.floor((Date.now()-start)/1000);$('#timer').textContent=[Math.floor(elapsed/3600),Math.floor(elapsed%3600/60),elapsed%60].map(pad).join(':')}
$('#workBtn').onclick=()=>{if(!start){start=Date.now();intv=setInterval(tick,1000);$('#workBtn').textContent='■ Stop Work';$('#workStatus').textContent='Work session in progress'}else{clearInterval(intv);tick();sessions.push({created:new Date().toISOString(),date:day(),seconds:elapsed});save();start=null;elapsed=0;$('#timer').textContent='00:00:00';$('#workBtn').textContent='▶ Start Work';$('#workStatus').textContent='Session saved';renderWork()}};
function renderWorkout(){let t=workouts.filter(w=>Date.now()-w.created<604800000).reduce((a,w)=>a+w.duration,0);$('#week').textContent=t+' min';$('#count').textContent=workouts.length;$('#dashWorkout').textContent=workouts.filter(w=>w.date===day()).reduce((a,w)=>a+w.duration,0)+' min';$('#workoutList').innerHTML=workouts.slice().sort((a,b)=>b.created-a.created).map(w=>`<div class="row"><div><b>${esc(w.name)}</b><p>${esc(w.details||'Workout')} · ${fmt(w.created)}</p></div><b>${w.duration} min</b></div>`).join('')||'<p style="color:var(--m)">No workouts logged yet.</p>'}
$('#workoutForm').onsubmit=e=>{e.preventDefault();workouts.unshift({created:Date.now(),date:day(),name:$('#wname').value.trim(),duration:+$('#wdur').value,details:$('#wdetail').value.trim()});save();e.target.reset();$('#workoutModal').classList.remove('open');renderWorkout()};
$('#menu').onclick=()=>{$('#drawer').classList.add('open');$('#overlay').classList.add('open')};function closeDrawer(){$('#drawer').classList.remove('open');$('#overlay').classList.remove('open')}$('#closeDrawer').onclick=closeDrawer;$('#overlay').onclick=closeDrawer;
function theme(t){document.body.dataset.theme=t;localStorage.setItem('j_theme',t)}$$('[data-theme]').forEach(x=>x.onclick=()=>theme(x.dataset.theme));$('#quickTheme').onclick=()=>theme(document.body.dataset.theme==='white'?'black':'white');
$('#editProfile').onclick=()=>{closeDrawer();$('#profileName').value=localStorage.getItem('j_name')||'Jashu';open('profileModal')};$('#profileForm').onsubmit=e=>{e.preventDefault();localStorage.setItem('j_name',$('#profileName').value.trim()||'Jashu');$('#profileModal').classList.remove('open')};
$('#export').onclick=()=>{let d={app:'Jashu',version:2,exportedAt:new Date().toISOString(),name:localStorage.getItem('j_name')||'Jashu',notes,playlists,sessions,workouts,theme:document.body.dataset.theme};let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:'application/json'}));a.download='jashu-backup-'+day()+'.json';a.click();closeDrawer()};
$('#import').onclick=()=>$('#file').click();$('#file').onchange=e=>{let r=new FileReader;r.onload=()=>{try{let d=JSON.parse(r.result);if(!Array.isArray(d.notes))throw 0;notes=d.notes;playlists=d.playlists||[{id:'fav',name:'Favourites',notes:[]}];sessions=d.sessions||[];workouts=d.workouts||[];if(d.name)localStorage.setItem('j_name',d.name);if(d.theme)theme(d.theme);save();render();alert('Import successful.')}catch{alert('Invalid Jashu backup file.')}};r.readAsText(e.target.files[0]);e.target.value='';closeDrawer()};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');theme(localStorage.getItem('j_theme')||'black');render();